const fileData = {
    "name":"root",
    "isFolder":true,
    "items":[
        {
            "name":"public",
            "isFolder":true,
            "items":[
                {
                    "name":"index.html",
                    "isFolder":false,
                    "items":[]
                },
                {
                    "name":"abc.svg",
                    "isFolder":false,
                    "items":[]
                }
            ]
        },
        {
            "name":"components",
            "isFolder":true,
            "items":[
                {
                    "name":"product.tsx",
                    "isFolder":false,
                    "items":[]
                },
                {
                    "name":"Billing.tsx",
                    "isFolder":false,
                    "items":[]
                }
            ]
        },
        {
            "name":"package.json",
            "isFolder":false,
            "items":[]
        }
    ]
}

export default fileData